### ISSUE TITLE
syz out of mem example over ZZ

### ISSUE THREAD

**Issue by jakobkroeker** [adipopescu/To-Do-List#62]
```
ring rng = (integer),(x,y,z),(rp(3),C);
intvec op = 100663296,10321;
 option(set, op) ;
 option() ;
 // option() ;//options: redTail intStrategy redefine loadLib usage prompt
ideal I = -12*z^4-11*x^3-10*x,3*y*z^2-15*x*y^2*z-13;
def syzI = syz (I);

quit;

```

or 

```
ideal I = -z^4-x^3-5*x,3*y*z^2-10*x*y^2*z-13;
```

**Comment by adipopescu** [comment]
First ideal: with option prot it looks like it will finish (till now 40 GB Memory). Maybe leave it later on a bigger  RAM computer?

Will test now the second example

**Comment by adipopescu** [comment]
So..after 60 GB RAM, first example, really looks like it is going to finish. 

Same in the second example.

You just need enough memory

**Comment by jakobkroeker** [comment]
> you just need enough memory

ok.
Just notice that the same example in Macaulay2 takes less than 100 MB and finishes in about 3 seconds. 

Therefore I suspect (but have no proof, and also I might be wrong) that in Singular the example finishes only by luck and there is a bug in Singular's implementation...

Of course the example is too complicated to allow an analysis of the issue.
But fortunately I posted here several other examples which might be simple enough
to catch the issue.

```
R = ZZ[z,y,x, MonomialOrder=>Lex]  -- lex is same as rp with reversed variable list

  I = ideal{-12*z^4-11*x^3-10*x,3*y*z^2-15*x*y^2*z-13};

S = syz gens I;
(gens I)*S==0
quit;
```

**Comment by adipopescu** [comment]
I will take a looktomorrow  at it to see what goes wrong in this case. And why it takes so long.

**Comment by jakobkroeker** [comment]
> I will take a looktomorrow at it to see what goes wrong in this case. And why it takes so long. 

I suggest to look at the simpler failing examples first. If more examples are needed, I will try to generate them.

(The constraint is that I moved to industry and only have spare time on weekends to 
work on this.)

Jakob

**Comment by adipopescu** [comment]
I had a really good look at it. 
I tried to compute just the std instead of syz and this is what i got:

M2: result immediate (goes just to degree 21), result 20 polys
Singular: with redTail activated it takes 2-3 minutes, goes over degree 60, result 20 polys

i compared the two results:

reduce(M2, Singular) = 0;
reduce(Singular, M2) != 0.
reduce(input ideal, M2) != 0.

I guess that M2 has a currupted tail and because of that it finishes really quick with a wrong Standard Basis. 

Not even the leading terms are the same (see no 14,15,16,17):

lead(M2);
_[1]=742500y8x7
_[2]=1403619360zx6
_[3]=68546400000zy
_[4]=228488000zyx
_[5]=351520zyx4
_[6]=6854640000zy2
_[7]=878800zy2x2
_[8]=260zy2x3
_[9]=52zy2x4
_[10]=zy2x5
_[11]=26364000zy3
_[12]=13000zy3x
_[13]=1300zy3x2
_[14]=110zy4x3
_[15]=15zy4x4
_[16]=4000zy5x
_[17]=300zy5x2
_[18]=52z2
_[19]=z2y
_[20]=4z4

lead(Singular);
_[1]=742500y8x7
_[2]=1403619360zx6
_[3]=68546400000zy
_[4]=228488000zyx
_[5]=351520zyx4
_[6]=6854640000zy2
_[7]=878800zy2x2
_[8]=260zy2x3
_[9]=52zy2x4
_[10]=zy2x5
_[11]=26364000zy3
_[12]=13000zy3x
_[13]=1300zy3x2
_[14]=10zy4x3
_[15]=zy4x4
_[16]=1000zy5x
_[17]=100zy5x2
_[18]=52z2
_[19]=z2y
_[20]=4z4
